apiVersion: v1
kind: Pod
metadata:
  name: cephfs-example
spec:
  containers:
  - name: cephfs-pod
    image: httpd:buster
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - 192.168.1.1:6789
      - 192.168.1.2:6789
      - 192.168.1.3:6789
      - 192.168.1.4:6789
      user: kubernetes
      secretRef:
        name: ceph-secret
      readOnly: false
      path: "/kubernetes"